name: CustomKitDuels
version: 1.0.0
main: com.yourname.customkitduels.CustomKitDuels
api-version: 1.21
author: moiz
description: custom kit dueling plugin for minecraft 1.21.4 - made with love by moiz

commands:
  customkit:
    description: main command for customkit
    usage: /<command> [subcommand]
    permission: customkitduels.use
    permission-message: you don't have permission to use this command.

permissions:
  customkitduels.use:
    description: allows basic use of customkit
    default: true
  customkitduels.admin:
    description: allows admin commands for customkit
    default: op
    children:
      - customkitduels.use